backend:
  name: github
  repo: mrhut10/futuresFineFurniture

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: assets

display_url: https://futuresfinefurniture.netlify.com

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name : blog
    label : Blog
    folder : collections/blog
    create : true
    slug: "{{year}}-{{slug}}"
    fields :
      - { name: "title", label: "Title", }
      - { name: "thumbnail", label: "Featured Image", widget: "image", required: false, }
      - { name: "body", label: "Body", widget: "markdown", }
